name: Cache Node and NPM Dependencies
description: "This action allows to cache both Node and NPM dependencies based on the package-lock.json file."
inputs:
  node-version:
    description: NodeJS version to use
    required: true
    default: 20.x
  working-dir:
    description: "The working directory of the application"
    required: false
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Cache dependencies
      if: cache-dependencies
      uses: actions/cache@v4
      with:
        path: "${{ inputs.working-dir }}/react-app/node_modules"
        key: deps-node-modules-${{ hashfiles(format('0/1', inputs.working-dir, 'package-lock.json' )) }}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash