name: "01 - Building Blocks"

#event trigger section
on:
  # Triggers the workflow on push or workflow_dispatch ( manual trigger)
  # push:
  #   branches:
  #   - main
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow contains two jobs
  echo-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Say Hello"
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
    - name: "Say goodbye"
      run: echo "Goodbye!"
