name: 04 -  Using Actions
on:
    push:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                path: ../../04-using-actions
                submodules: true
            - name: Printing Folders
              run: | 
                ls -ltra ${{github.workspace}}