name: 07 -  Using Expressions
# if debug is true 'ON' else 'false'
run-name: 07 - dUsing Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF'}}

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{inputs.debug == false}}
              run: | 
                echo "Triggered by: ${{github.event_name}}"
                echo "Branch: ${{github.ref_name}}"
                echo "Commit SHA:${{github.sha}}"
                echo "Runner OS:${{runner.os}}"
            - name: '[debug] Print when triggered'
              if: ${{inputs.debug == true && github.ref_name == 'main'}}
              run: echo I was triggered from main
            - name: 'Greeting'
              run: echo 'Hello World'