name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        strategy:
            fail-fast: true # if 1 kv pair fails, immediately fail the whole matrix
            matrix:
                node-version: [ '18.x', '19.x', '20.x' ]
                os: [ubuntu-latest, windows-latest ]
                include:
                  - node-version: 16.x
                    os: ubuntu-latest
                  - node-version: 21.x
                    os: ubuntu-latest
                    tag: experimental
                
        runs-on: ${{ matrix.os }}
        steps:
            - name: Setup Node 
              uses: actions/setup-node@v4
              with:
              # Version Spec of the version to use in SemVer notation.
              # It also admits such aliases as lts, latest, nightly and canary builds
              # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
                  node-version: ${{ matrix.node-version }}
            - name: Perform some tests 
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                sleep 10s
              shell: bash
            - name: Upload test results
              run: echo Uploading test results
            - name: Fail if experimental
              if: ${{ matrix.tag == 'experimental' }}
              run: exit -1
    include-example:
        strategy:
            matrix:
                color:
                    - red
                    - green
                shape:
                    - circle
                    - square
                size:
                    - small
                    - large
                include:
                    - opacity: 50
                    - color: red
                      shape: triangle
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
        runs-on: ubuntu-latest
        steps:
            - name: dummy steps
              run: |
                echo ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}