name: Working with Matrices
on:
    workflow_dispatch:
jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        steps:
            - name: test 
              run: echo initial setup 