name: 16 - Working with Environments
on:
    workflow_dispatch:
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: staging
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Deploying to staging
              run: | 
                echo "Env variable: ${{env.my-env-value}}"
    e2e-tests:
        runs-on: ubuntu-latest
        environment: staging
        needs:
            - deploy-staging
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: E2E tests
              run: | 
                echo "Running E2E"
    deploy-prod-backend1:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: |
                echo Deploying to prod backend1
    deploy-prod-backend2:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: |
                echo Deploying to prod backend2
    deploy-prod-frontend:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        env:
            my-env-value: ${{vars.MY_ENV_VALUE || 'default value'}}
        steps:
            - name: Echo vars
              run: |
                echo Deploying to prod frontend
            
            
