name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options:
                    - dev
                    - prod
env:
    working_directory: 17-custom-actions/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working_directory}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: "./.github/actions/composite-cache-deps"
              with: 
                node-version: 20.x
                #default run does not apply to custom actions
                working-dir: ${{env.working_directory}}
            - name: test
              run: npm run test
            - name: build
              run: npm run build
            

